#########################
### Workspace & Binds ###
#########################

bindd = SUPER, G, Go to gaming workspace, workspace, name:Games
bindd = SUPER SHIFT, G, Send to gaming workspace, movetoworkspacesilent, name:Games

# Close special workspace on moving to another workspace
bindd = SUPER, G, Close special workspace when going to regular workspace, exec, hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .specialWorkspace.name' | sed 's/special://' | xargs -I [] hyprctl dispatch togglespecialworkspace []############

####################
### Window rules ###
####################

# Games
$GAME = (steam_app.*)|(gamescope)|cs2|minecraft
windowrule = immediate on, match:class $GAME # tear all games
#windowrule = fullscreen, class:$GAME # fullscreen all games
windowrule = render_unfocused on, match:class $GAME # Stop FPS loss
windowrule = workspace name:Games, match:class $GAME # put all games on workspace "Games"

# Launchers
$LAUNCHERS = steam|.*prismlauncher.*
windowrule = workspace 6 silent, match:class $LAUNCHERS

# Third party tools
windowrule = workspace 2, match:initial_title Cheat Engine.*
windowrule = tile on, match:initial_title Cheat Engine.*
windowrule = group set [always], match:initial_title Cheat Engine.*

#############
### Extra ###
#############

###################
### Performance ###
###################
misc:render_unfocused_fps = 30 # Raise minimum FPS of rule "renderunfocused"
