#########################
### Workspace & Binds ###
#########################

bindd = SUPER, G, Go to gaming workspace, workspace, name:Games
bindd = SUPER SHIFT, G, Send to gaming workspace, movetoworkspacesilent, name:Games

####################
### Window rules ###
####################

# Games
$GAME = (steam_app.*)|(gamescope)|cs2|minecraft
windowrule {
	name = games
	match:class = $GAME

	immediate = on
	fullscreen = on
	render_unfocused = on
	workspace = name:Games

}

# Launchers
$LAUNCHERS = steam|.*prismlauncher.*
windowrule = workspace 6 silent, match:class $LAUNCHERS

# Third party tools
windowrule = workspace 2, match:initial_title Cheat Engine.*
windowrule = tile on, match:initial_title Cheat Engine.*
windowrule = group set [always], match:initial_title Cheat Engine.*

#############
### Extra ###
#############

###################
### Performance ###
###################
misc:render_unfocused_fps = 30 # Raise minimum FPS of rule "renderunfocused"
